export const labels = {
    heading: "Customer Rewards Program",
    customers: "Customers",
    transaction: "Transactions for selected month",
    custId: "Customer ID: ",
    total: "Total: ",
    points: "points",
    lastThree: "Last 3 Months",
    id: "ID",
    date: "Date",
    amount: "Amount",
    points2: "Points",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
}